### ISSUE TITLE
Invalid Composition

### ISSUE THREAD

**Issue by praharshbhatt** [CameronStuartSmith/flutter_lottie#15]
App crashes with the following logs:

> E/AndroidRuntime(11357): java.lang.IllegalStateException: Unable to parse composition
> E/AndroidRuntime(11357): 	at com.airbnb.lottie.LottieAnimationView$2.onResult(LottieAnimationView.java:68)
> E/AndroidRuntime(11357): 	at com.airbnb.lottie.LottieAnimationView$2.onResult(LottieAnimationView.java:66)
> E/AndroidRuntime(11357): 	at com.airbnb.lottie.LottieTask.notifyFailureListeners(LottieTask.java:167)
> E/AndroidRuntime(11357): 	at com.airbnb.lottie.LottieTask.access$300(LottieTask.java:26)
> E/AndroidRuntime(11357): 	at com.airbnb.lottie.LottieTask$1.run(LottieTask.java:142)
> E/AndroidRuntime(11357): 	at android.os.Handler.handleCallback(Handler.java:873)
> E/AndroidRuntime(11357): 	at android.os.Handler.dispatchMessage(Handler.java:99)
> E/AndroidRuntime(11357): 	at android.os.Looper.loop(Looper.java:193)
> E/AndroidRuntime(11357): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
> E/AndroidRuntime(11357): 	at java.lang.reflect.Method.invoke(Native Method)
> E/AndroidRuntime(11357): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
> E/AndroidRuntime(11357): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
> E/AndroidRuntime(11357): Caused by: java.io.FileNotFoundException: flutter_assets/assets/lottie animations/splashscreen.json
> E/AndroidRuntime(11357): 	at android.content.res.AssetManager.nativeOpenAsset(Native Method)
> E/AndroidRuntime(11357): 	at android.content.res.AssetManager.open(AssetManager.java:744)
> E/AndroidRuntime(11357): 	at android.content.res.AssetManager.open(AssetManager.java:721)
> E/AndroidRuntime(11357): 	at com.airbnb.lottie.LottieCompositionFactory.fromAssetSync(LottieCompositionFactory.java:100)
> E/AndroidRuntime(11357): 	at com.airbnb.lottie.LottieCompositionFactory$1.call(LottieCompositionFactory.java:81)
> E/AndroidRuntime(11357): 	at com.airbnb.lottie.LottieCompositionFactory$1.call(LottieCompositionFactory.java:79)
> E/AndroidRuntime(11357): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> E/AndroidRuntime(11357): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
> E/AndroidRuntime(11357): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
> E/AndroidRuntime(11357): 	at java.lang.Thread.run(Thread.java:764)
>

**Comment by pradyukrish** [comment]
> E/AndroidRuntime(11357): Caused by: java.io.FileNotFoundException: flutter_assets/assets/lottie animations/splashscreen.json

This exception means that Lottie was unable to find the asset file.
Verify that the asset splashscreen.json is present in assets/lottie animations/ and it is added in your app's pubspec yaml.
