### ISSUE TITLE
Please update to Swift

### ISSUE THREAD

**Issue by magicleon94** [CameronStuartSmith/flutter_lottie#9]
Newer versions (>2.5.3) of lottie-ios break the plugin because of the migration to Swift.

**Comment by kimthangatm** [comment]
https://github.com/CameronStuartSmith/flutter_lottie/blob/d1ec99b5d4de3c2a81773855cc050fd635fe0091/ios/flutter_lottie.podspec#L16

1. Clone `flutter_lottie` to your computer :
2. Change `s.dependency 'lottie-ios'` to `s.dependency 'lottie-ios', '2.5.0'` in `flutter_lottie/ios/flutter_lottie.podspec`
3. Change pubspec.yaml

```
flutter_lottie: 
    path: '../flutter_lottie'
```

4. cd YOUR/project/ios and delete `Podfile.lock` and run `pod install`
5. Get Package to update dependency in local

**Comment by Raullg98** [comment]
This will solve your problem @magicleon94, check the iOS part
https://github.com/ko2ic/image_downloader/wiki#your-appdelegate-is-the-case-of-objective-c
